name: smart_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: 4.11.0
  firebase_storage: 11.4.0
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.7
  quickalert: ^1.0.2
  custom_navigation_bar: ^0.8.2
  lottie: ^2.7.0
  image_cropper: ^5.0.0
  infinite_scroll_pagination: ^4.0.0
  cloud_functions: ^4.5.2
  http: ^1.1.0
  quill_html_editor: ^2.2.7
  flutter_advanced_drawer: ^1.3.5
  font_awesome_flutter: ^10.6.0
  auto_height_grid_view: ^1.0.0
  intl: ^0.18.1
  logger: ^2.0.2+1

dev_dependencies: 
  flutter_lints: 3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/smartmanagerlogo.png"
  min_sdk_android: 21